"""Render measured evidence; refuses incomplete or failed audit records."""
import collections as C,csv,json,pathlib
A=pathlib.Path(__file__).resolve().parent
read=lambda p:json.loads((A/p).read_text())
r=read('reconciliation.json'); l=read('ledger.json'); p=read('population-v2.json'); n=read('no-cds-independent.json'); m=read('b5_full_a40_v1.merge-receipt.json'); protected=read('protected-artifacts-v2.json')
o=json.loads((A.parent/'b5_population_audit_20260905.json').read_text())
for j in [r,l,n,protected,read('supplement.json'),read('margins-recomputed.json'),read('merge-status-v2.json')]: assert j['status']=='PASS'
assert all(l['checks'].values()) and all(p['checks'].values())
lines=[]
def text(s=''):lines.append(s)
def table(head,rows):
 text('| '+' | '.join(head)+' |');text('| '+' | '.join(['---']*len(head))+' |')
 for row in rows: text('| '+' | '.join(str(x) for x in row)+' |')
 text()
def fmt(v):return f'{v:,}'
def delta(v):return f'{v:+,}'
text('# A40 verification — 2026-09-06')
text('\n**PASS: completion interface resolved, +924 rows reconciled, full verification completed. Not frozen or adopted.** No unexplained row additions, removals, or shared-row semantic differences remain in the tested attribution. All nine current-source replays agree with their databases; the merged validator has zero violations; every additional ledger check below passed.\n')
text('New database on `gpu`: `/home/pgl/scratch1/wyim/transgenic_data/b5/a40_20260905_v1/merged/b5_full_a40_v1.db`. The output metadata is `b5_full_a40_v1.merge-receipt.json`, explicitly a merge receipt, not an adopted freeze. No `.DONE` markers were created. No commit, protocol edit, freeze/adoption, historical artifact edit, or alignment work occurred.\n')
text('## Completion evidence — option (a)')
text('\nThe merger now accepts `--build-status <root>/provenance/build-status.json`. This is cleaner than deriving markers: the A40 driver already records completion there, and a second mutable completion object would add another freshness problem. The original build snapshot remains unchanged. The revised merger was executed from `<root>/audit/verification-source/`; only the merger and its tests differ from the copied snapshot. The actual argv, cwd, timestamps, exit 0, and every executed Python source hash are in [merge-status-v2.json](a40_audit/merge-status-v2.json).\n')
text('The gate requires aggregate SUCCESS/exit 0, an exact species set with no missing/duplicate/extra records, integer species exit 0 and `completion_ok is true`, the correct DB path, the recorded rejection hash, and a separate manifest exactly matching the database manifest. It then validates each current DB afresh, requires `ok=true`, zero violations and that species only, and hashes the DB before/after validation and again before merging. Evidence hashes and complete per-species validation results are embedded in the [merge receipt](a40_audit/b5_full_a40_v1.merge-receipt.json). Invalid evidence cannot fall back to the legacy marker path. All nine passed. The legacy path remains for historical callers; the A40 invocation explicitly uses the status gate.\n')
text('Completion tests: **20/20 passed**, including missing/duplicate species, failed/incomplete status, wrong database, changed rejection evidence, changed manifest evidence, and failed fresh validation. The original attempt exited 1 for missing `Athaliana.DONE`; that interface failure is resolved by the new gate, not by inventing markers. The confirmed original build duration remains 04:59:28–06:50:21 UTC (1h50m53s).\n')
text('## The +924 rows — causal reconciliation')
text('\nThe allocation below uses an explicit order: **historical corpus → #55 with the old masking population → #55 + #56**. The intermediate is an in-memory counterfactual, not another built or adopted database. Its sole change from the snapshot replay is to restore unconditional cap-exclusion of no-CDS loci; seeds, input files, flags and all other rules are identical. Every intermediate row shared with the historical database has identical audited row semantics; every added intermediate row is one of the 97 recorded ordering-reject coordinates (or its RC). There are zero intermediate removals and zero other additions or shared-row changes. This is evidence for causation, not an assignment of an unexplained remainder to #56.\n')
rows=[]
for sp,v in r['species'].items():rows.append([sp,fmt(v['old_rows']),fmt(v['new_rows']),delta(v['delta']),v['ordering_forward'],v['ordering_rc'],delta(v['mask_population_added']-v['mask_population_removed']),v['unexplained_added']+v['unexplained_removed']])
table(['Species','Historical','New','Δ rows','#55 forward','#55 RC','#56 net','Other'],rows+[['Total','272,224','273,148','+924',97,63,'+764',0]])
text('**#55 contributes +160, not +194:** all 97 ordering-only forward windows survive; only 63 qualify for isoform-only RC. Vvinifera contributes 78 forward +44 RC; the other three affected species contribute 19 forward +19 RC. **#56 contributes +829 forward −65 RC = +764**. Together: +926 forward −2 RC = +924.\n')
text('### Direct recovery in the final corpus is a different count\n')
table(['Species','Historical rejects','Final forward at old coordinate','Final RC at old coordinate','Final fate'],[[sp,len(v['ordering_fates']),sum(x['current_forward'] for x in v['ordering_fates']),sum(x['current_rc'] for x in v['ordering_fates']),'All retained' if sp!='Vvinifera' else 'All 78 coordinates absent from changed grid'] for sp,v in r['species'].items() if v['ordering_fates']])
text('Thus **19 old rejected coordinates +19 RC rows are directly recovered in the final corpus**. All 78 Vvinifera coordinates disappear after #56 changes empty-sampling RNG consumption and subsequent offsets. The +122 ordering-only Vvinifera rows are among the rows removed by the population counterfactual; they are not claimed as physically retained final rows. Equivalently, using direct final recovery, +924 = +38 direct ordering recovery +886 Vvinifera population/order interaction. The table above exposes that interaction instead of double-counting it. All 97 individual fates and old rejection messages are in [reconciliation.json](a40_audit/reconciliation.json). The historical 13 ties +84 decreasing-span failures are all covered; new canonical-order rejections are zero.\n')
text('### Vvinifera: what #56 actually changes\n')
v=r['species']['Vvinifera']; c=v['counterfactual_stats']; now=v['current_stats']
text('Old Vvinifera 32,116 → ordering-only 32,238 → final 33,002. The last step adds 32,627 row keys, removes 31,863, and changes the contents of 30 shared rows, net +764. The large coordinate turnover is measured RNG/grid movement, not 32,627 newly discovered biological loci. The complete row-level transition file is [Vvinifera.population-row-changes.tsv](a40_audit/Vvinifera.population-row-changes.tsv).\n')
table(['#56 transition','Forward added','RC added','Forward removed','RC removed','Net'],[
 ['Different tile coordinates (grid absent in other replay)',24919,7706,24091,7770,'+764'],
 ['Same coordinate: previously empty-sampled, now retained',2,0,0,0,'+2'],
 ['Same coordinate: now rejected for mask fraction',0,0,1,1,'−2'],
 ['Shared rows with changed sequence/label/counters',0,0,0,0,'0 (24 forward +6 RC changed)'],
 ['Total',24921,7706,24092,7771,'+764']])
table(['Forward-window accounting','#55 only','Final #55 + #56','Δ'],[[k,fmt(c.get(k,0)),fmt(now.get(k,0)),delta(now.get(k,0)-c.get(k,0))] for k in ['candidate_windows','empty_sampled_out','mask_fraction_rejected','window_cap_rejected','forward_retained','rc_rows','component_added','leak','hard','decoy','dup_collapsed']])
text('Conservation: candidate windows −3, empty-sampling drops −878, mask-fraction drops +46, cap drops unchanged → +829 retained forward windows; RC −65 → +764 rows. Component propagation increases by 1,697 forward occurrences. These mechanisms interact: the report does not invent an additive “component-only row count” separate from RNG, flank masking, and sampling when they jointly determine a tile. The disjoint per-row fate transitions above and the one-change counterfactual establish the row cause.\n')
text('All five species with no ordering or population change reproduce exactly. Athaliana, Ppatens and Ptrichocarpa have only their measured ordering additions. **Unexplained additions = 0; unexplained removals = 0; unexplained shared-row semantic changes = 0.** Each current replay matches row fingerprints, `window_genes`, `gene_key_map`, tile blocks and rejection records. Remaining provenance/static row fields and unchanged historical input references were checked separately in [supplement.json](a40_audit/supplement.json).\n')
text('## No-CDS population and stored masks')
text('\n**PASS: 6,205/6,205 original Vvinifera no-CDS loci**, assigned 4,600 train /634 valid /971 test; all 6,205 are eligible in the new population, with zero coding memberships and zero decoy memberships. None is hard-flagged. Denominator 41,766 →47,971 (+6,205); leak/hard-union numerator 15,346 →16,951 (+1,605 =634+971); realised rate `min(0.05, numerator/denominator/3)` is **0.05 before and after**, verified rather than presumed. Per-species denominators/numerators/rates are retained in reconciliation JSON.\n')
st=n['occurrences']
table(['No-CDS occurrence check','Forward','RC'],[[k,fmt(st.get(key+'_forward',0)),fmt(st.get(key+'_RC',0))] for k,key in [('Complete locus in retained tile','complete_occurrences'),('Leak seed','leak'),('Hard (including overlaps with leak)','hard'),('Hard only','hard_only'),('Leak ∪ hard seed','leak_hard_union'),('Masked after component closure','component_masked')]])
text('The independent audit examines all **25,253 Vvinifera forward windows**, reconstructs masking seeds and fixed-point interval-graph closure independently of the builder’s component sweep, and checks actual stored N coverage over every masked complete locus. No labelled coding member remains in a masked component. All 4,850 forward +1,615 RC masked no-CDS occurrences have coverage; the RC conclusion also uses exhaustive actual RC-sequence equality. Of these, closure adds 1,218 forward +437 RC occurrences beyond the leak/hard seed union. Hard and hard-only counts are both zero; union is not double-counted. See [no-cds-independent.json](a40_audit/no-cds-independent.json).\n')
text('The existing complete-locus guarantee is preserved: partial loci crossing tile edges are outside its scope. Same-split non-hard no-CDS loci are not unconditional mask seeds; some are masked through closure. No stronger protection is claimed.\n')
text('## Rows, empty targets and token ledger')
text('\nFull species × split × tier × orientation counts are provided for both corpora: [historical TSV](a40_audit/old-rows-species-split-tier-orientation.tsv), [new TSV](a40_audit/new-rows-species-split-tier-orientation.tsv). These enumerate the full joint distribution, not only marginal sums.\n')
table(['Split','Old rows','New rows','Δ rows','Old empty','New empty','Δ empty'],[[s,fmt(o['totals']['rows_by_split'][s]),fmt(p['totals']['rows_by_split'][s]),delta(p['totals']['rows_by_split'][s]-o['totals']['rows_by_split'][s]),dict(l['old']['empty_by_split'])[s],dict(l['new']['empty_by_split'])[s],delta(dict(l['new']['empty_by_split'])[s]-dict(l['old']['empty_by_split'])[s])] for s in ['train','valid','test']])
text('Rows: **272,224 →273,148 (+924)**. Forward: **188,145 →189,071 (+926)**; RC: **84,079 →84,077 (−2)**. Empty targets: **25,159 →26,057 (+898)**, '+f"{25159/272224*100:.4f}% →{26057/273148*100:.4f}%"+'. Every one of the **26,057 actual empty rows** was passed through the snapshot dataset’s decoder path and produced exactly `<s> <empty> </s>` (three tokens). The cached read adapter supplied the actual stored row; only the unrelated encoder tokenizer was stubbed to avoid model downloads.\n')
table(['Species','Old token max','New token max','Δ max','Old stored tokens','New actual/stored tokens','Δ tokens'],[[a[0],a[1],z[1],delta(z[1]-a[1]),fmt(a[2]),fmt(z[2]),delta(z[2]-a[2])] for a,z in zip(l['old']['token_by_species'],l['new']['token_by_species'])])
text('All **273,148 actual tokenizer lengths equal stored counts**, with no unknown tokens, truncation, or cap violations. Maximum remains **5,920** (cap 8,192); Vvinifera’s species maximum moves 2,574 →2,785 (+211). Total stored/actual tokens: **119,582,469 →119,593,692 (+11,223)**. #58’s extra actual token on the same new corpus is **26,057**, not the old 25,159; stored counts already used three tokens. Using the old two-token empty convention, the historical actual total would be 119,557,310, so the combined old-actual →new-actual movement is +36,382. This last comparison is derived from the known old convention, not a claim that the old tokenizer was re-executed here.\n')
text('## Mask counters, rejection counters and N totals\n')
table(['Counter (RC included)','Old','New','Δ'],[[k,fmt(o['mask_counters_total'][k]),fmt(p['mask_counters_total'][k]),delta(p['mask_counters_total'][k]-o['mask_counters_total'][k])] for k in p['mask_counters_total']])
table(['Rejection class','Old','New','Δ'],[[k,fmt(o['rejections_total'].get(k,0)),fmt(p['rejections_total'].get(k,0)),delta(p['rejections_total'].get(k,0)-o['rejections_total'].get(k,0))] for k in sorted(set(o['rejections_total'])|set(p['rejections_total']))])
text('No additional gene/window/feature-cap rejection class appears (gene-cap count 0); transcript-cap 333 and token-cap 3 are unchanged. No-CDS rejection diagnostics remain 6,205 coding exclusions, not masking exclusions. Empty-sampling and duplicate-collapse accounting are separately recorded by replay; Vvinifera accounts for the sampling change. Per-species mask sums, tile counts carrying each counter, and rejection breakdowns are in [population-v2.json](a40_audit/population-v2.json); forward-only replay counters avoid accidentally double-counting RC in causal comparisons.\n')
a=sum(x[1] for x in l['old']['N_by_species']);z=sum(x[1] for x in l['new']['N_by_species']);ab=sum(x[2] for x in l['old']['N_by_species']);zb=sum(x[2] for x in l['new']['N_by_species'])
text(f'Stored uppercase N bases, RC included: **{a:,} →{z:,} ({z-a:+,})**; stored sequence bases **{ab:,} →{zb:,} ({zb-ab:+,})**. N fraction **{a/ab:.8%} →{z/zb:.8%}**. Per-species values are in ledger JSON. These count natural Ns plus introduced masks; they are not a count of newly masked biological bases.\n')
text('## Assignments, labelled populations, diagnostics and structural acceptance')
text('\n**All three must-not-move quantities pass:** 334,642 nominal assignments; train 213,702 /valid 29,153 /test 91,787; strict 3,430. All source tables and the merged table retain gene-split content SHA256 `61766859a1d712b49f3fdbeb457067d00e604d53a0298af614c28bff2ea1deee`. All original gene-key maps match historical sources. Source FASTA/GFF references, hashes, split hash, QC families, RC mode, ordering version, window policy and DuckDB version are unchanged.\n')
table(['Assigned split','Old ever-labelled','New ever-labelled','Δ','New coverage'],[[s,fmt(o['evaluation_population']['split_totals'][s]['ever_labelled_genes']),fmt(p['evaluation_population']['split_totals'][s]['ever_labelled_genes']),delta(p['evaluation_population']['split_totals'][s]['ever_labelled_genes']-o['evaluation_population']['split_totals'][s]['ever_labelled_genes']),str(p['evaluation_population']['split_totals'][s]['pct'])+'%'] for s in ['train','valid','test']])
mat=C.Counter()
for x in p['evaluation_population']['gene_split_by_tile_split']:mat[x['gene_split'],x['tile_split']]+=x['unique_genes']
table(['Gene assignment','Train tiles','Valid tiles','Test tiles'],[[s,fmt(mat[s,'train']),fmt(mat[s,'valid']),fmt(mat[s,'test'])] for s in ['train','valid','test']])
text('Strict ever-labelled remains **431/3,430**, Δ0. Test-tile target universe **54,188 →54,265 (+77)** =34,655 train-assigned (+49) +4,590 valid-assigned (+13) +15,020 test-assigned (+15). These unions across tile splits must not be summed to infer ever-labelled totals because a gene can occur in several tile splits. Original reference test-gene length and transcript-count distributions were regenerated per species; missing reference gene keys =0. The detailed labelled/unlabelled distributions and hashed reference paths are in population JSON. No metric denominator or evaluation universe was redefined.\n')
text('**#57 PASS:** all-original-gene denominator 334,642 and maximum length 196,414 nt are unchanged. Length-bound exceedances remain 3,418 /653 /86 for tiers 30,720 /61,440 /129,024. The historical no-edge-credit margin upper bounds remain 2,034 /434 /44. Exact FASTA-edge-aware counters were recomputed for all nine species from original coordinates and current FASTA and match every stored diagnostic; for these inputs their aggregate values also happen to be 2,034 /434 /44. Missing contigs =0. These are separate calculations, not an assumption that an upper bound equals an exact count. See [margins-recomputed.json](a40_audit/margins-recomputed.json).\n')
table(['Structural invariant','Result'],[
 ['Authoritative orthogroup split integrity; strict assignments','PASS, nine fresh source validators and merged validator; zero violations'],
 ['Strict holdouts and forbidden train/valid label leakage','PASS, orientation-aware membership joins; no gene labelled below its assigned split'],
 ['Excluded maize species/models','PASS, none'],
 ['Window/sequence lengths and caps','PASS; observed tiers 30,720 /61,440 /129,024; tokenizer cap 8,192'],
 ['Required labels, no orphan membership, row-key uniqueness','PASS; no NULL/invalid labels, no orphan window_genes, no duplicate keys'],
 ['RC membership, sequence and split correspondence','PASS exhaustively; every RC has its forward row and identical gene membership'],
 ['Canonical labels and RC involution','PASS for all 273,148 labels, not only paired RC labels'],
 ['Merged rn contiguous and deterministic','PASS; 1..273,148, 273,148 distinct values; each equals species offset + source rank ordered by source rn'],
 ['Source replay and historical row-delta conservation','PASS 9/9; zero unexplained row differences']])
text('Full results: [ledger.json](a40_audit/ledger.json), [reconciliation.json](a40_audit/reconciliation.json), and the population report.\n')
text('## Artifact identity and protected objects\n')
table(['New artifact field','Value'],[['Rows','273,148'],['Bytes',fmt(m['file_bytes'])],['File MD5',m['file_md5']],['geneList content SHA256',m['geneList_content_sha256']],['gene_split content SHA256',m['gene_split_content_sha256']]])
text('The old merged DB is unchanged: **23,491,260,416 bytes**, `mtime_ns=1788422329816219148`, freshly recomputed MD5 **ebf4fb511073c546d05e3fa0fc0e4258**. All nine old source DB MD5s match the old freeze. All original executed source hashes were rechecked; all 18 QC SHA256s still match the previous verified invocation (whose MD5s matched the historical freeze). See [protected-artifacts-v2.json](a40_audit/protected-artifacts-v2.json). The original A40 source snapshot and historical source objects were only read. The protocol, `data/freeze/b5_full_v1.freeze.json`, and alignment results were not edited.\n')
text('## Limits and final disposition\n')
text('No failing acceptance check was bypassed. No unexplained row delta remains. The #55/#56 additive allocation is explicitly order-dependent; the final-coordinate recovery count is reported separately. Component closure, RNG stream changes and masking can interact, so no unsupported independent component-only row increment is claimed. The N-coverage guarantee applies to complete eligible loci under the existing recipe, not edge-partial loci. File-layout hashes and recipe/manifest metadata are expected to move; the old artifact is preserved.\n')
text('**Verified replacement artifact available for review; no commit, protocol amendment, freeze or adoption performed.**')
(A.parent/'a40_verification_20260906.md').write_text('\n'.join(lines)+'\n')
